# https://trasparente.github.io/default/github/2020/12/19/actions.html
name: Play turn
on:
  schedule:
    # Run at 00:01 06:01 12:01 18:01 UTC every day
    - cron: '1 0/6 * * *'
jobs:
  update:
    name: manifest turn
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - name: checkout
        uses: actions/checkout@v3

      # Get UNIX
      - name: Get current unix
        id: unix
        run: echo "unix_seconds=$(date +%s)" >> $GITHUB_OUTPUT

      # Get Dice
      - name: Get dice
        id: dice
        run: echo "dice_value=$(expr 1 + $RANDOM % 6)" >> $GITHUB_OUTPUT

      # Get Dice Bis
      - name: Get dice Bis
        id: diceb
        run: echo "dice_value_b=$(expr 1 + $RANDOM % 6)" >> $GITHUB_OUTPUT

      # Get Dice Tris
      - name: Get dice Tris
        id: dicet
        run: echo "dice_value_t=$(expr 1 + $RANDOM % 6)" >> $GITHUB_OUTPUT

      # write to CSV file
      - name: Write to CSV file
        uses: gr2m/write-csv-file-action@v1.0.0
        with:
          path: "_data/turns.csv"
          columns: run, unix, dice, diceb, dicet
          run: ${{ github.run_id }}
          unix: ${{ steps.unix.outputs.unix_seconds }}
          dice: ${{ steps.dice.outputs.dice_value }}
          diceb: ${{ steps.diceb.outputs.dice_value_b }}
          dicet: ${{ steps.dicet.outputs.dice_value_t }}

      # COMMIT
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
